name: Build Autofalcon for macOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # bump to 20 since selenium-webdriver requires >=20

      - name: Install dependencies
        run: npm install

      - name: Build universal macOS app
        run: npm run dist 
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: Autofalcon-dmg
          path: dist/*.dmg

      - name: Upload macOS ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Autofalcon-zip
          path: dist/*.zip
